# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - acb2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build API
        run: cd packages/api && yarn build
      - name: Create package tgz
        run: cd packages/api && yarn pack && mv package.tgz actual-api.tgz
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: actual-api
          path: packages/api/actual-api.tgz

  crdt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build CRDT
        run: cd packages/crdt && yarn build
      - name: Create package tgz
        run: cd packages/crdt && yarn pack && mv package.tgz actual-crdt.tgz
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: actual-crdt
          path: packages/crdt/actual-crdt.tgz

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build Web
        run: ./bin/package-browser
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: actual-web
          path: packages/desktop-client/build
      - name: Upload Build Stats
        uses: actions/upload-artifact@v4
        with:
          name: build-stats
          path: packages/desktop-client/build-stats

  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build Server
        run: cd packages/sync-server && yarn build
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: sync-server
          path: packages/sync-server/build

  deploy:
    runs-on: ubuntu-latest
    needs: [web]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: actual-web

      - name: Zip artifact
        run: zip -r release.zip
        path: .

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61B9F0D22EE84723A3BBE1107DC1FA77 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CB64AF18F85E47D0A977B8BEA0549DA3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2AAA427B82894523B7A1C04C18CD4905 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'acb1'
          slot-name: 'Production'
          package: release.zip
          
